
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'SPECIES REAL INTEGER PLUS HYPHEN ARROWTO ARROWFROM EQUALS VOLUME TIME TIMEDIFF DETERMINISTICstmt : SPECIES EQUALS numberstmt : VOLUME EQUALS INTEGERstmt : TIME EQUALS numberstmt : TIMEDIFF EQUALS numberstmt : DETERMINISTICnumber : REAL\n            | INTEGERstmt : stmt : molecules HYPHEN number ARROWTO molecules\n            | molecules ARROWFROM number HYPHEN molecules\n            | molecules HYPHEN ARROWTO molecules\n            | molecules ARROWFROM HYPHEN moleculesmolecules : molecule PLUS molecules\n                 | molecule\n                 | molecule : INTEGER SPECIES\n                | SPECIES'
    
_lr_action_items = {'SPECIES':([0,4,17,25,27,30,32,],[2,12,29,29,29,29,29,]),'VOLUME':([0,],[3,]),'TIME':([0,],[5,]),'TIMEDIFF':([0,],[6,]),'DETERMINISTIC':([0,],[7,]),'$end':([0,1,7,9,12,17,18,19,20,21,22,23,25,27,28,29,30,31,32,33,34,35,],[-8,0,-5,-14,-16,-15,-1,-6,-7,-2,-3,-4,-15,-15,-13,-17,-15,-11,-15,-12,-9,-10,]),'HYPHEN':([0,2,8,9,12,16,17,19,20,26,28,29,],[-15,-17,15,-14,-16,27,-15,-6,-7,32,-13,-17,]),'ARROWFROM':([0,2,8,9,12,17,28,29,],[-15,-17,16,-14,-16,-15,-13,-17,]),'INTEGER':([0,10,11,13,14,15,16,17,25,27,30,32,],[4,20,21,20,20,20,20,4,4,4,4,4,]),'EQUALS':([2,3,5,6,],[10,11,13,14,]),'PLUS':([2,9,12,29,],[-17,17,-16,-17,]),'REAL':([10,13,14,15,16,],[19,19,19,19,19,]),'ARROWTO':([15,19,20,24,],[25,-6,-7,30,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'stmt':([0,],[1,]),'molecules':([0,17,25,27,30,32,],[8,28,31,33,34,35,]),'molecule':([0,17,25,27,30,32,],[9,9,9,9,9,9,]),'number':([10,13,14,15,16,],[18,22,23,24,26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stmt","S'",1,None,None,None),
  ('stmt -> SPECIES EQUALS number','stmt',3,'p_stmt_concentration','crnlex.py',62),
  ('stmt -> VOLUME EQUALS INTEGER','stmt',3,'p_stmt_volume','crnlex.py',68),
  ('stmt -> TIME EQUALS number','stmt',3,'p_stmt_time','crnlex.py',75),
  ('stmt -> TIMEDIFF EQUALS number','stmt',3,'p_stmt_dt','crnlex.py',82),
  ('stmt -> DETERMINISTIC','stmt',1,'p_stmt_deterministic','crnlex.py',89),
  ('number -> REAL','number',1,'p_number','crnlex.py',94),
  ('number -> INTEGER','number',1,'p_number','crnlex.py',95),
  ('stmt -> <empty>','stmt',0,'p_stmt_empty','crnlex.py',99),
  ('stmt -> molecules HYPHEN number ARROWTO molecules','stmt',5,'p_stmt_reaction','crnlex.py',103),
  ('stmt -> molecules ARROWFROM number HYPHEN molecules','stmt',5,'p_stmt_reaction','crnlex.py',104),
  ('stmt -> molecules HYPHEN ARROWTO molecules','stmt',4,'p_stmt_reaction','crnlex.py',105),
  ('stmt -> molecules ARROWFROM HYPHEN molecules','stmt',4,'p_stmt_reaction','crnlex.py',106),
  ('molecules -> molecule PLUS molecules','molecules',3,'p_molecules_rule','crnlex.py',117),
  ('molecules -> molecule','molecules',1,'p_molecules_rule','crnlex.py',118),
  ('molecules -> <empty>','molecules',0,'p_molecules_rule','crnlex.py',119),
  ('molecule -> INTEGER SPECIES','molecule',2,'p_molecule_rule','crnlex.py',132),
  ('molecule -> SPECIES','molecule',1,'p_molecule_rule','crnlex.py',133),
]
